version: '3.8'
services:
 db:
    container_name: pg_cont2
    image: postgres
    restart: "no"
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${PG_USER}
      POSTGRES_PASSWORD: ${PG_PASS}
      POSTGRES_DB: ${PG_DBNAME}
    ports:
      - "${PG_PORT}:5432"
    volumes:
      - /tmp/pg_data/:/tmp/
      - pg_data:/var/lib/postgres/data
        # pgadmin:
        #   container_name: pgadmin4_container
        #   image: dpage/pgadmin4:5.5
        #   restart: always
        #   environment:
        #     PGADMIN_DEFAULT_EMAIL: ${PGADM_MAIL}
        #     PGADMIN_DEFAULT_PASSWORD:  ${PGADM_PASS}
        #     PGADMIN_LISTEN_PORT: 80
        #   ports:
        #     - "${PGADM_PORT}:80"
        #   volumes:
        #     - pgadmin-data:/var/lib/pgadmin
volumes:
  pg_data:
    #  pgadmin-data:
